### ISSUE TITLE
Update Please

### ISSUE THREAD

**Issue by cinprens** [MX-Goliath/MoA-Ollama#1]
Update Please Openwebui mixture agent if you live^^ 

"""
MODERATION TEAM NOTE:
WE'VE HAD SEVERAL REPORTS THAT THIS FUNCTION NO LONGER WORKS ON LATER VERSIONS OF OPENWEBUI.
WE INVITE THE AUTHOR TO PLEASE UPDATE THIS FUNCTION OR IT WILL BE REMOVED.
"""

write this note open web ui

**Comment by MX-Goliath** [comment]
Hello! I am not the author of the original function in openwebui, so I created my own working version:
https://openwebui.com/f/superbr/moa_v2

This version uses three layers: the first layer has three models generating initial responses, the second layer has three models refining the previous answers, and the final layer has a single model. If you need to adjust the number of layers, the number of models in each layer, or the prompts, you can do so in the following lines:

```python
layers = [3, 3]  
layer_prompts = [
    "Answer the user's question.",
    "Check the previous answer to the user's question and completely rewrite it, correcting errors and inaccuracies.",
]
```

For example, change it to:

```python
layers = [3, 3, 4]  
layer_prompts = [
    "Answer the user's question.",
    "Check the previous answer to the user's question and completely rewrite it, correcting errors and inaccuracies.",
    "Complete and expand on this answer",
]
```

The final layer is only responsible for combining responses and consists of a single model, so it is not recommended to modify it.

**Comment by MX-Goliath** [comment]
> Обновите, пожалуйста, Openwebui mix agent, если вы живы^^
> 
> """ ПРИМЕЧАНИЕ КОМАНДЫ МОДЕРАЦИИ: МЫ ПОЛУЧИЛИ НЕСКОЛЬКО СООБЩЕНИЙ О ТОМ, ЧТО ЭТА ФУНКЦИЯ БОЛЬШЕ НЕ РАБОТАЕТ В ПОСЛЕДНИХ ВЕРСИЯХ OPENWEBUI. МЫ ПРОСИМ АВТОРА ОБНОВИТЬ ЭТУ ФУНКЦИЮ, ИНАЧЕ ОНА БУДЕТ УДАЛЕНА. """
> 
> написать эту заметку открыть веб-интерфейс

Hello! I am not the author of the original function in openwebui, so I created my own working version:
https://openwebui.com/f/superbr/moa_v2

This version uses three layers: the first layer has three models generating initial responses, the second layer has three models refining the previous answers, and the final layer has a single model. If you need to adjust the number of layers, the number of models in each layer, or the prompts, you can do so in the following lines:

```python
layers = [3, 3]  
layer_prompts = [
    "Answer the user's question.",
    "Check the previous answer to the user's question and completely rewrite it, correcting errors and inaccuracies.",
]
```

For example, change it to:

```python
layers = [3, 3, 4]  
layer_prompts = [
    "Answer the user's question.",
    "Check the previous answer to the user's question and completely rewrite it, correcting errors and inaccuracies.",
    "Complete and expand on this answer",
]
```

The final layer is only responsible for combining responses and consists of a single model, so it is not recommended to modify it.
